/////////////////////////////////////////////////////////////
/*

Code Summary:  Supplies the structure and function declarations for each function in the ArduinoSend.cpp file.


Author: original outline generated by gemini -- modified by Graeme Appel

Last Updated: 7/13/2026
*/

/////////////////////////////////////////////////////////////


#ifndef ARDUINO_SEND_HPP
#define ARDUINO_SEND_HPP

#include <string>
#include <cstdint>
#include <fstream>

// Argument mapping: sendTargetCoordinates(uint16_t object_id, int16_t command_parameter, int16_t command_call_id)

class ArduinoSend {
private:
    int serial_fd; // defines a serial file descriptor that stores a number for the serial port connection between the Jetson and the Arduino.
                   // This is referenced when using write() and read() functions later in the actual code
    std::string port_name; // Allocates space for a string variable that stores the literal directory path of the hardware link on your Jetson (e.g., "/dev/ttyACM0").
    bool tracking_mode_active; // Tracks whether the ecosystem has transitioned to tracking mode

public:
    ArduinoSend(const std::string& port = "/dev/ttyACM0"); // class constructor
    ~ArduinoSend(); // destructor ensures that link to linux software is cleanly severed when all operations are finished to prevent errors

    bool initializePort(); 
    bool sendTargetCoordinates(uint16_t id, int16_t  x, int16_t y, std::ofstream& logFile);
    void closePort();
    void flushCache();
    double readMotorPosition(std::ofstream& logFile);
    void logTelemetry(std::ofstream& logFile, int frameNum, double motorPos, bool isMotorTest);
};

#endif
