/////////////////////////////////////////////////////////////
/*
Code Summary:


Author: original outline generated by gemini -- modified by Graeme Appel

Last Updated: 6/23/2026
*/

/////////////////////////////////////////////////////////////

#include "ArduinoSend.hpp" // includes header file
#include <iostream> // standard C++ library
#include <cstring> // allows for processing of strings and character blocks

// Included libraries for working in Linux code with the Jetson
#ifndef _WIN32
#include <fcntl.h> // file control library -- linux treats everything as files so this provides tools for opening different files and accessing and manipulating necessary file information
#include <termios.h> // this enables all terminal and I/O interfaces which allows for manual control over setting and looking at parameters and connection ports
#include <unistd.h> // helps link together the linux and C++ interfaces and supplies the functions like write() and close()
#endif
/////////////////////////////////////////////////////////////




ArduinoSend::ArduinoSend(const std::string& port) : serial_fd(-1), port_name(port) {}

ArduinoSend::~ArduinoSend() {
    closePort();
}

bool ArduinoSend::initializePort() {
    // Open read/write, block execution on read, prevent it from becoming a controlling terminal
    serial_fd = open(port_name.c_str(), O_RDWR | O_NOCTTY);
    if (serial_fd == -1) {
        std::cerr << "[ERROR] ArduinoSend: Failed to open port " << port_name << std::endl;
        return false;
    }

    struct termios options;
    tcgetattr(serial_fd, &options);

    // Set standard Baud Rate to 115200 (Matches Arduino Serial.begin)
    cfsetispeed(&options, B115200);
    cfsetospeed(&options, B115200);

    // Enforce 8N1 Data layout
    options.c_cflag &= ~PARENB;
    options.c_cflag &= ~CSTOPB;
    options.c_cflag &= ~CSIZE;
    options.c_cflag |= CS8;

    // Turn off Hardware/Software Flow Control completely
    options.c_cflag &= ~CRTSCTS;
    options.c_iflag &= ~(IXON | IXOFF | IXANY);

    // Force Raw Processing Mode (Crucial for streaming pure binary integers safely)
    options.c_cflag |= (CLOCAL | CREAD);
    options.c_lflag &= ~(ICANON | ECHO | ECHOE | ISIG);
    options.c_oflag &= ~OPOST;

    // Apply configuration changes immediately
    tcsetattr(serial_fd, TCSANOW, &options);
    return true;
}

bool ArduinoSend::sendTargetCoordinates(uint16_t id, int16_t x, int16_t y) {
    if (serial_fd == -1) return false; // exits the sending coordinates function early if no USB connection descriptor number is found preventing program from crashing

    // Prompting output messages to check with data package (i.e object ID and coordinates) are being sent at any given time from the Jetson to the Arduino
    std::cout << "sending coords to arduino (" << id << ") -- ";
    std::cout << "x: " << x << " y: " << y << std::endl;



    // Construct a packet matching 16-bit integers
    // We send a tiny marker payload: Start byte '!', X bytes, Y bytes, End byte '\n'


    // Note: Standard layout for serial UART information is:    Start Bit -- 8 Bits of info -- Parity Bit (in specifications above always set to 0)-- Stop bit
    // The arduino UNO and Jetson cannot transmit or receive 16 bit binary data of the form XXXXXXXX XXXXXXXX so in stead each set of 8 bits is made into a section stored in sections of "buffer" and then put together again

    uint8_t buffer[8]; // unsigned 8 bit integer that splits up each 16 bit x and y coordinate into two parts to be able to be transmitted over the processors of both the Jetson and the Arduino

    buffer[0] = '!';                         // Start Frame Marker -- interacts with arduino portion of the code and Arduino only starts to process and store a piece 
                                             // of data if it sees this starting symbol (in binary) first. Prevents mistakes for if the arduino starts picking up a transmission
                                             // halfway through, then it knows where to start collecting a given set of x,y coordinate numbers

    // Split 16-bit ID into two 8-bit bytes
    buffer[1] = (id >> 8) & 0xFF;              // ID High Byte
    buffer[2] = id & 0xFF;                     // ID Low Byte


    buffer[3] = (x >> 8) & 0xFF;             // X High Byte (largest powers in binary to decimal) -- the x >> 8 shifts all the bits 8 to the left effectively making the higher bit into the lower bit temporarily and then the 0xFF
                                             //  is 1111 1111 in binary which when applied with the bitwise & operator, this only keeps bits with any 1's in them meaning the high bit which was moved to the lower bit is then kept 
                                             // and all the other information is discarded.
    buffer[4] = x & 0xFF;                    // X Low Byte -- same process as above is applied except no rightward shifting by 8 is applied so in this case, the only bit that is eliminated is the higher bit keeping the lower bit.
    buffer[5] = (y >> 8) & 0xFF;             // Y High Byte -- same process as above but for the input y coordinate
    buffer[6] = y & 0xFF;                    // Y Low Byte -- same process as above but for the input y coordinate
    buffer[7] = '\n';                        // End Frame Marker -- acts nearly identically to the start frame marker and tells the arduino to not accept a piece of binary data unless it is framed at the start by a "!" and ended with a "\n"

    int bytes_written = write(serial_fd, buffer, sizeof(buffer)); // using a built in Linux function called write() this takes the data which was previously re-packaged in the previous steps and writes/sends the information from the Jetson to the Arduino
                                                                  // This function takes in the serial_fd to know which channel the information is being sent on.
                                                                  // It uses buffer to know what the information is that is being sent and uses sizeof(buffer) to know the amount of data that is being sent along the desired channel
    return (bytes_written == sizeof(buffer)); // returns a bool variable value to the system to ensure that the size of the written data is equal to the size of the stored process data. If they are not the same this means that there
                                              // is likely some sort of wire disconnected which stops running the system allowing it to be fixed/debugged
}

void ArduinoSend::closePort() {
    if (serial_fd != -1) { // checks to see if serial_fd is NOT off (i.e has actually been running and connected) before trying to close it down
        close(serial_fd); // linux function that cuts off the connection to both of the communicating devices 
        serial_fd = -1; // resets the serial value to -1 or OFF so that no duplicate close commands occur
    }
}
