/////////////////////////////////////////////////////////////
/*
Code Summary:


Author: originally generated by gemini -- modified by Graeme Appel

Last Updated: 6/22/2026
*/

/////////////////////////////////////////////////////////////

#include "ArduinoReceive.hpp" // includes header file
#include <iostream> // standard C++ library
#include <cstring> // allows for processing of strings and character blocks

// Included libraries for working in Linux code with the Jetson
#ifndef _WIN32
#include <fcntl.h> // file control library -- linux treats everything as files so this provides tools for opening different files and accessing and manipulating necessary file information
#include <termios.h> // this enables all terminal and I/O interfaces which allows for manual control over setting and looking at parameters and connection ports
#include <unistd.h> // helps link together the linux and C++ interfaces and supplies the functions like write() and close()
#endif
/////////////////////////////////////////////////////////////




/**
 * Arduino Receiver & PID Driver Code
 * Matches Jetson Serial Packet Structure:
 * [0]   '!'       (Start Frame Marker)
 * [1-2] ID        (16-bit Target Identifier, High/Low Bytes)
 * [3-4] X Coord   (16-bit Signed Integer, High/Low Bytes)
 * [5-6] Y Coord   (16-bit Signed Integer, High/Low Bytes)
 * [7]   '\n'      (End Frame Marker)
 */


// Global declarations for target tracking states
uint16_t activeTargetID = 0;
int16_t  targetXCoord   = 0;
int16_t  targetYCoord   = 0;

// --- STEP 1: INITIALIZE HARDWARE SUBSYSTEMS ---
void setup() {
  // Initialize Serial UART connection. Must perfectly match the B115200 
  // speed forced by tcsetattr() inside ArduinoSend::initializePort().
  Serial.begin(115200);
  
  // Optional: Pin initializations for system hardware (gimbals, servos, etc.)
  // pinMode(9, OUTPUT); 
}

// --- STEP 2: STREAM PROCESSING RECEPTION LOOP ---
void loop() {
  // Check if at least one complete 8-byte packet is waiting in the buffer
  if (Serial.available() >= 8) {
    
    // Peek or read the first byte to verify it's our designated frame marker
    if (Serial.read() == '!') {
      
      // Read the 16-bit Target ID (Split across 2 bytes)
      uint8_t id_high = Serial.read();
      uint8_t id_low  = Serial.read();
      
      // Read the 16-bit X pixel coordinate (Split across 2 bytes)
      uint8_t x_high  = Serial.read();
      uint8_t x_low   = Serial.read();
      
      // Read the 16-bit Y pixel coordinate (Split across 2 bytes)
      uint8_t y_high  = Serial.read();
      uint8_t y_low   = Serial.read();
      
      // Read the terminating character
      uint8_t end_marker = Serial.read();

      // Enforce frame validation alignment before trusting data integrity
      if (end_marker == '\n') {
        
        // Reconstruct the 16-bit words by shifting the High Byte up 8 bits 
        // and merging the Low Byte using a bitwise OR operation.
        activeTargetID = (uint16_t)((id_high << 8) | id_low);
        targetXCoord   = (int16_t)((x_high << 8) | x_low);
        targetYCoord   = (int16_t)((y_high << 8) | y_low);

        // Dispatch the synchronized coordinates straight into the tracking loop
        executePIDControl(activeTargetID, targetXCoord, targetYCoord);
      }
      else {
        // Alignment error recovery: discard data frame to resynchronize stream
        // This prevents tracking drift if bytes get dropped mid-flight.
        while (Serial.available() > 0 && Serial.read() != '\n');
      }
    }
  }
}

// --- STEP 3: ACTUATION & TRACKING COMPUTATION ---
void executePIDControl(uint16_t id, int16_t x, int16_t y) {
  // This function triggers every single time a clean target frame updates.
  // Insert your mathematical PID error differences here.
  
  // Example: 
  // float errorX = target_center_x - x;
  // float outputX = calculatePID(errorX);
  // servoX.write(outputX);
}
